deployment:
  tasks:
    - export DEPLOYPATH=/home/topjeuco/public_html/

    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp app_v2.js $DEPLOYPATH
    - /bin/cp styles_v2.css $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
