deployment:
  tasks:
    - export DEPLOYPATH=/home/topjeuco/public_html/

    - /bin/cp index_v10.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp app_v10.js $DEPLOYPATH
    - /bin/cp styles_v10.css $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
