deployment:
  tasks:
    - export DEPLOYPATH=/home/topjeuco/public_html/

    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp app.minified.js $DEPLOYPATH
    - /bin/cp styles.minified.css $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp -R reviews $DEPLOYPATH/reviews/ 